services:
  postgres:
    image: postgres:15-alpine
    container_name: gem_postgres
    environment:
      - POSTGRES_DB=gem_db
      - POSTGRES_USER=gem_user
      - POSTGRES_PASSWORD=gem_password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - gem-network
  
  redis:
    image: redis:alpine
    container_name: gem_redis
    ports:
      - "6379:6379"
    networks:
      - gem-network

networks:
  gem-network:
    driver: bridge
