services:
  postgres:
    image: postgres:15-alpine
    container_name: gem_postgres
    environment:
      - POSTGRES_DB=gem_db
      - POSTGRES_USER=gem_user
      - POSTGRES_PASSWORD=gem_password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - gem-network
  
  redis:
    image: redis:alpine
    container_name: gem_redis
    ports:
      - "6379:6379"
    networks:
      - gem-network
  
  prometheus:
    image: prom/prometheus:latest
    container_name: gem_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml # Monta il file creato prima
    extra_hosts:
      - "host.docker.internal:host-gateway" # Necessario per far vedere l'host al container
    networks:
      - gem-network
  
  grafana:
    image: grafana/grafana:latest
    container_name: gem_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Password default
    networks:
      - gem-network

networks:
  gem-network:
    driver: bridge
