global:
  scrape_interval: 5s # Legge le metriche ogni 5 secondi

scrape_configs:
  - job_name: "spring-boot-app"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8080"] # Punta alla mia macchina host 
